export { default as App } from './App';
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Shop } from './Shop'
export { default as About } from './About'
export { default as PrivacyAndLegal } from './PrivacyAndLegal'